activemq_servers_poll_enabled: False
activemq_servers:
  - url: "http://activemq-server:8161/admin/xml/queues.jsp"
    user: "User"
    passwd: "Password"
    comment: "Test activemq server"
zabbix_triggers_poll_enabled: False
zabbix_min_severity: 1
zabbix_servers:
  - url: "http://zabbix-server/api_jsonrpc.php"
    user: "user"
    passwd: "Password"
    comment: "Test zabbix server"
