---
name: on_event1
description: Rule firing on st2-chatops-misc.event1 when queue size too much
enabled: true
trigger:
    packs: "st2-chatops-misc"
    type: "st2-chatops-misc.event1"
criteria:
    trigger.size:
        pattern: 99
        type: "gt"
action:
    ref: "hubot.post_message"
    parameters:
        message: "WARNING queue {{trigger.name}} size is {{trigger.size}}! Queue consumers  {{trigger.consumers}}, server: {{trigger.url}}, comment: {{trigger.comment}}"
        channel: "general"
